### ISSUE TITLE
New Script Request - script to export events

### ISSUE THREAD

**Issue by jeremyweiss** [mailgun/scripts#1]
We need a script that allows users to export logs from the Event API endpoint and save them in a csv file.

Features requested:
* Ability to choose an event type or all events
* Ability to set dates or a date range
* Ability to select a single domain rather than the whole account

**Comment by alopez-84** [comment]
Had this one for a while, never did the pr :( 
[6505c94](https://github.com/alopez-84/scripts/pull/3/commits/6505c9449f67c3d700179de43b6030e652d43e25)
